openapi: 3.0.0
info:
  title: environment
  description: Documentation for meshery Cloud REST APIs
  contact:
    email: maintainers@meshery.io
  version: v0.6.394
servers:
  - url: https://cloud.meshery.io
    description: Meshery Cloud production server URL
  - url: https://staging-cloud.meshery.io
    description: Meshery Cloud staging server URL
  - url: http://localhost:9876
    description: Meshery Cloud development server URL (controlled via PORT environment variable)

security:
  - jwt: []

tags:
  - name: environments
    description: APIs for environments
components:
  responses:
    200:
      $ref: "../../v1alpha1/core/openapi.yml#/components/responses/200"
    400:
      $ref: "../../v1alpha1/core/openapi.yml#/components/responses/400"
    401:
      $ref: "../../v1alpha1/core/openapi.yml#/components/responses/401"
    500:
      $ref: "../../v1alpha1/core/openapi.yml#/components/responses/500"

  parameters:
    environmentId:
      name: environmentId
      in: path
      description: Environment ID
      schema:
        $ref: ../../v1alpha1/core/openapi.yml#/components/schemas/Id
      required: true
    search:
      $ref: ../../v1alpha1/core/openapi.yml#/components/parameters/search
    order:
      $ref: ../../v1alpha1/core/openapi.yml#/components/parameters/order
    page:
      $ref: ../../v1alpha1/core/openapi.yml#/components/parameters/page
    pagesize:
      $ref: ../../v1alpha1/core/openapi.yml#/components/parameters/pagesize
    orgIDQuery:
      name: orgID
      in: query
      description: User's organization ID
      schema:
        type: string
      required: true

  securitySchemes:
    jwt:
      type: http
      scheme: Bearer
      bearerFormat: JWT
  schemas:
    environment:
      $ref: "./environment.json"
    environmentConnectionMapping:
      $ref: "./environment_connection_mapping.json"
    environmentPayload:
      properties:
        name:
          $ref: ../../v1alpha1/core/openapi.yml#/components/schemas/Text
          description: An environment is a collection of resources. Provide a name that meaningfully represents these resources. You can change the name of the environment even after its creation.
        description:
          $ref: ../../v1alpha1/core/openapi.yml#/components/schemas/Text
          description: "An environment is a collection of resources, such as connections & credentail. Provide a detailed description to clarify the purpose of this environment and the types of resources it encompasses. You can modify the description at any Time. Learn more about environments [here](https://docs.meshery.io/concepts/logical/environments)."
        OrganizationID:
          type: string
          description: Select an organization in which you want to create this new environment. Keep in mind that the organization cannot be changed after creation.
          x-go-type-skip-optional-pointer: true
          x-go-name: OrgId
          x-oapi-codegen-extra-tags:
            json: organization_id
      required:
        - name
        - organizationID
    environmentPage:
      properties:
        page:
          $ref: ../../v1alpha1/core/openapi.yml#/components/schemas/number
        page_size:
          $ref: ../../v1alpha1/core/openapi.yml#/components/schemas/number
        total_count:
          $ref: ../../v1alpha1/core/openapi.yml#/components/schemas/number
        environments:
          type: array
          x-go-type-skip-optional-pointer: true
          items:
            $ref: "#/components/schemas/environment"

  requestBodies:
    environmentPayload:
      description: Body for creating environment
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/environmentPayload"

paths:
  /api/environments:
    post:
      tags:
        - environments
      operationId: CreateEnvironment
      summary: Create an environment
      description: Creates a new environment
      requestBody:
        $ref: "#/components/requestBodies/environmentPayload"
      responses:
        "201":
          description: Created environment
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/environment"
        "400":
          $ref: "#/components/responses/400"
        "500":
          $ref: "#/components/responses/500"
    get:
      tags:
        - environments
      operationId: GetEnvironments
      summary: Get all environments
      description: Gets all environments
      parameters:
        - $ref: "#/components/parameters/search"
        - $ref: "#/components/parameters/order"
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/pagesize"
        - $ref: "#/components/parameters/orgIDQuery"
      responses:
        "200":
          description: Environments
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/environmentPage"
        "401":
          $ref: "#/components/responses/401"
        "500":
          $ref: "#/components/responses/500"
