openapi: 3.0.0
info:
  title: environment
  description: Documentation for meshery Cloud REST APIs
  contact:
    email: maintainers@meshery.io
  version: v0.6.394
servers:
  - url: https://cloud.meshery.io
    description: Meshery Cloud production server URL
  - url: https://staging-cloud.meshery.io
    description: Meshery Cloud staging server URL
  - url: http://localhost:9876
    description: Meshery Cloud development server URL (controlled via PORT environment variable)

security:
  - jwt: []

tags:
  - name: environments
    description: APIs for environments
components:
  responses:
    200:
      $ref: "../../v1alpha1/core/openapi.yml#/components/responses/200"
    400:
      $ref: "../../v1alpha1/core/openapi.yml#/components/responses/400"
    401:
      $ref: "../../v1alpha1/core/openapi.yml#/components/responses/401"
    500:
      $ref: "../../v1alpha1/core/openapi.yml#/components/responses/500"

  parameters:
    environmentId:
      name: environmentId
      in: path
      description: Environment ID
      schema:
        $ref: ../../v1alpha1/core/openapi.yml#/components/schemas/Id
      required: true
    search:
      $ref: ../../v1alpha1/core/openapi.yml#/components/parameters/search
    order:
      $ref: ../../v1alpha1/core/openapi.yml#/components/parameters/order
    page:
      $ref: ../../v1alpha1/core/openapi.yml#/components/parameters/page
    pagesize:
      $ref: ../../v1alpha1/core/openapi.yml#/components/parameters/pagesize
    orgIDQuery:
      name: orgID
      in: query
      description: User's organization ID
      schema:
        type: string
      required: true

  securitySchemes:
    jwt:
      type: http
      scheme: Bearer
      bearerFormat: JWT
  schemas:
    environment:
      $ref: "./environment.json"
    environmentConnectionMapping:
      properties:
        ID:
          $ref: ../../v1alpha1/core/openapi.yml#/components/schemas/general_id
        environment_id:
          type: string
          format: uuid
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/gofrs/uuid
          x-oapi-codegen-extra-tags:
            db: environment_id
            json: environment_id
          x-go-type-skip-optional-pointer: true
        connection_id:
          type: string
          format: uuid
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/gofrs/uuid
          x-oapi-codegen-extra-tags:
            db: connection_id
            json: connection_id
          x-go-type-skip-optional-pointer: true
        created_at:
          $ref: ../../v1alpha1/core/openapi.yml#/components/schemas/Time
        updated_at:
          $ref: ../../v1alpha1/core/openapi.yml#/components/schemas/Time
        deleted_at:
          $ref: ../../v1alpha1/core/openapi.yml#/components/schemas/nullTime
    environmentPayload:
      properties:
        name:
          $ref: ../../v1alpha1/core/openapi.yml#/components/schemas/Text
          description: An environment is a collection of resources. Provide a name that meaningfully represents these resources. You can change the name of the environment even after its creation.
        description:
          $ref: ../../v1alpha1/core/openapi.yml#/components/schemas/Text
          description: "An environment is a collection of resources, such as connections & credentail. Provide a detailed description to clarify the purpose of this environment and the types of resources it encompasses. You can modify the description at any Time. Learn more about environments [here](https://docs.meshery.io/concepts/logical/environments)."
        organization_id:
          type: string
          description: Select an organization in which you want to create this new environment. Keep in mind that the organization cannot be changed after creation.
          x-go-type-skip-optional-pointer: true
          x-go-name: OrgId
          x-oapi-codegen-extra-tags:
            json: organization_id
      required:
        - name
        - organization_id
    environmentPage:
      properties:
        page:
          $ref: ../../v1alpha1/core/openapi.yml#/components/schemas/number
        page_size:
          $ref: ../../v1alpha1/core/openapi.yml#/components/schemas/number
        total_count:
          $ref: ../../v1alpha1/core/openapi.yml#/components/schemas/number
        environments:
          type: array
          x-go-type-skip-optional-pointer: true
          items:
            x-go-type: Environment
            $ref: "#/components/schemas/environment"
    environmentUpdatePayload:
      properties:
        name:
          $ref: ../../v1alpha1/core/openapi.yml#/components/schemas/Text
          description: Name of the environment
        description:
          $ref: ../../v1alpha1/core/openapi.yml#/components/schemas/Text
          description: Environment description

  requestBodies:
    environmentPayload:
      description: Body for creating environment
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/environmentPayload"
    environmentUpdatePayload:
      description: Body for updating environment
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/environmentUpdatePayload"

paths:
  /api/environments:
    post:
      tags:
        - environments
      operationId: CreateEnvironment
      summary: Create an environment
      description: Creates a new environment
      requestBody:
        $ref: "#/components/requestBodies/environmentPayload"
      responses:
        "201":
          description: Created environment
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/environment"
        "400":
          $ref: "#/components/responses/400"
        "500":
          $ref: "#/components/responses/500"
    get:
      tags:
        - environments
      operationId: GetEnvironments
      summary: Get all environments
      description: Gets all environments
      parameters:
        - $ref: "#/components/parameters/search"
        - $ref: "#/components/parameters/order"
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/pagesize"
        - $ref: "#/components/parameters/orgIDQuery"
      responses:
        "200":
          description: Environments
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/environmentPage"
        "401":
          $ref: "#/components/responses/401"
        "500":
          $ref: "#/components/responses/500"

  /api/environments/{environmentId}:
    get:
      tags:
        - environments
      operationId: GetEnvironmentByID
      summary: Get an environment by ID
      description: Gets an environment by its ID
      parameters:
        - $ref: "#/components/parameters/environmentId"
        - $ref: "#/components/parameters/orgIDQuery"
      responses:
        "200":
          description: Environment
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/environment"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "../../v1alpha1/core/openapi.yml#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
    delete:
      tags:
        - environments
      operationId: DeleteEnvironment
      summary: Delete an environment
      description: Deletes an environment by its ID
      parameters:
        - $ref: "#/components/parameters/environmentId"
      responses:
        "200":
          description: Environment deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/environment"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "../../v1alpha1/core/openapi.yml#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
    put:
      tags:
        - environments
      operationId: UpdateEnvironment
      summary: Update an environment
      description: Updates the environment
      parameters:
        - $ref: "#/components/parameters/environmentId"
      requestBody:
        $ref: "#/components/requestBodies/environmentUpdatePayload"
      responses:
        "200":
          description: Environment updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/environment"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "../../v1alpha1/core/openapi.yml#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"

  /api/environments/{environmentId}/connections:
    get:
      tags:
        - environments
      operationId: GetConnectionsOfEnvironment
      summary: Get all connections assigned to an environment
      description: Gets all connections assigned to an environment with pagination and filtering
      parameters:
        - $ref: "#/components/parameters/environmentId"
        - $ref: "#/components/parameters/search"
        - $ref: "#/components/parameters/order"
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/pagesize"
      responses:
        "200":
          description: Connections in Environment
          content:
            application/json:
              schema:
                $ref: "../connection/openapi.yml#/components/schemas/ConnectionPage"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "../../v1alpha1/core/openapi.yml#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"

  /api/environments/{environmentId}/connections/{connectionId}:
    post:
      tags:
        - environments
      operationId: AssignConnectionToEnvironment
      summary: Assign a connection to an environment
      description: Assigns a connection to an environment
      parameters:
        - $ref: "#/components/parameters/environmentId"
        - name: connectionId
          in: path
          schema:
            $ref: "../../v1alpha1/core/openapi.yml#/components/schemas/Id"
          required: true
          description: Connection ID
      responses:
        "200":
          description: Connection assigned successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/environmentConnectionMapping"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "../../v1alpha1/core/openapi.yml#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
    delete:
      tags:
        - environments
      operationId: UnassignConnectionFromEnvironment
      summary: Unassign a connection from an environment
      description: Unassigns a connection from an environment
      parameters:
        - $ref: "#/components/parameters/environmentId"
        - name: connectionId
          in: path
          schema:
            $ref: "../../v1alpha1/core/openapi.yml#/components/schemas/Id"
          required: true
          description: Connection ID
      responses:
        "200":
          description: Connection unassigned successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/environmentConnectionMapping"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "../../v1alpha1/core/openapi.yml#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
