openapi: 3.0.0
info:
  title: Meshery Cloud
  description: Documentation for meshery Cloud REST APIs
  contact:
    email: support@layer5.io
  version: v0.6.394
servers:
  - url: https://meshery.layer5.io
    description: Meshery Cloud production server URL
  - url: https://staging-meshery.layer5.io
    description: Meshery Cloud staging server URL
  - url: http://localhost:9876
    description: Meshery Cloud development server URL (controlled via PORT environment variable)
security:
  - jwt: []
tags:
  - name: applications
    description: APIs for applications
components:
  securitySchemes:
    jwt:
      type: http
      scheme: Bearer
      bearerFormat: JWT
  schemas:
    mesheryApplication:
      properties:
        id:
          $ref: ./common/core.yml#/components/schemas/id
        user_id:
          $ref: ./common/core.yml#/components/schemas/id
        application_file:
          $ref: ./common/core.yml#/components/schemas/text
          description: Application file
        name:
          $ref: ./common/core.yml#/components/schemas/text
          description: Pattern Name
        location:
          $ref: ./common/core.yml#/components/schemas/map_object
        visibility:
          $ref: ./common/core.yml#/components/schemas/text
        source_type:
          enum: [k8s_manifest, docker_compose, helm_chart]
          description: Source type (K8s manifest, Helm chart, Docker compose)
        source_content:
          type: string
          format: byte
          description: Source content
        catalog_data:
          $ref: ./common/core.yml#/components/schemas/map_object
        created_at:
          $ref: ./common/core.yml#/components/schemas/time
        updated_at:
          $ref: ./common/core.yml#/components/schemas/time
    mesheryApplicationPage:
      allOf:
        - $ref: ./common/core.yml#/components/schemas/resultsPage
        - type: object
          properties:
            applications:
              type: array
              items:
                $ref: "#/components/schemas/mesheryApplication"

  requestBodies:
    mesheryApplicationRequestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              url:
                $ref: ./common/core.yml#/components/schemas/endpoint
              path:
                $ref: ./common/core.yml#/components/schemas/text
              save:
                type: boolean
              application_data:
                $ref: "#/components/schemas/mesheryApplication"
              source_type:
                $ref: ./common/core.yml#/components/schemas/text

paths:
  /api/content/applications:
    post:
      tags:
        - applications
      operationId: UpsertApplication
      summary: Upsert Application
      description: It will insert the application if not present else it will update the matching entry
      requestBody:
        $ref: "#/components/requestBodies/mesheryApplicationRequestBody"
      responses:
        "200":
          description: Upserted application
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/mesheryApplication"
        "400":
          $ref: ./common/responses.yml#/400
        "401":
          $ref: ./common/responses.yml#/401
        "500":
          $ref: ./common/responses.yml#/500
    get:
      tags:
        - applications
      operationId: GetApplications
      summary: Get Applications
      description: Get paginated applications
      parameters:
        - $ref: ./common/parameters.yml#/components/parameters/page
        - $ref: ./common/parameters.yml#/components/parameters/page_size
        - $ref: ./common/parameters.yml#/components/parameters/search
        - $ref: ./common/parameters.yml#/components/parameters/order
      responses:
        "200":
          description: Applications
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/mesheryApplicationPage"
        "401":
          $ref: ./common/responses.yml#/401
        "500":
          $ref: ./common/responses.yml#/500
  /api/content/applications/upload/{id}:
    post:
      tags:
        - applications
      operationId: UpsertApplicationSourceContent
      summary: Upsert application source content
      description: Upserts only application source content
      parameters:
        - $ref: ./common/parameters.yml#/components/parameters/id
      requestBody:
        description: Body for upserting meshery application source content
        required: true
        content:
          text/plain:
            schema:
              $ref: "#/components/schemas/mesheryApplication/properties/source_content"
      responses:
        "200":
          $ref: ./common/responses.yml#/200
        "400":
          $ref: ./common/responses.yml#/400
        "401":
          $ref: ./common/responses.yml#/401
        "500":
          $ref: ./common/responses.yml#/500
  /api/content/applications/download/{id}:
    get:
      tags:
        - applications
      operationId: GetApplicationSourceContent
      summary: Get application source content
      description: Get application source content
      parameters:
        - $ref: ./common/parameters.yml#/components/parameters/id
      responses:
        "200":
          description: application source content associated with ID
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/mesheryApplication/properties/source_content"
        "400":
          $ref: ./common/responses.yml#/400
        "401":
          $ref: ./common/responses.yml#/401
        "500":
          $ref: ./common/responses.yml#/500
  /api/content/applications/{id}:
    get:
      tags:
        - applications
      operationId: GetApplication
      summary: Get application by ID
      description: Get application by ID
      parameters:
        - $ref: ./common/parameters.yml#/components/parameters/id
      responses:
        "200":
          description: application associated with ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/mesheryApplication"
        "400":
          $ref: ./common/responses.yml#/400
        "401":
          $ref: ./common/responses.yml#/401
        "404":
          $ref: ./common/responses.yml#/404
        "500":
          $ref: ./common/responses.yml#/500
    delete:
      tags:
        - applications
      operationId: DeleteApplication
      summary: Delete application by ID
      description: Delete application associated with ID
      parameters:
        - $ref: ./common/parameters.yml#/components/parameters/id
      responses:
        "200":
          description: Deleted application
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/mesheryApplication"
        "400":
          $ref: ./common/responses.yml#/400
        "401":
          $ref: ./common/responses.yml#/401
        "404":
          $ref: ./common/responses.yml#/404
        "500":
          $ref: ./common/responses.yml#/500
